# Generated by Django 5.2.7 on 2025-11-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Complete name of the user', max_length=255, verbose_name='full name')),
                ('email', models.EmailField(help_text='Email address for communication', max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='phone')),
                ('address', models.TextField(blank=True, help_text='Physical address', verbose_name='address')),
                ('registration_number', models.CharField(help_text='Unique identifier for the library user', max_length=50, unique=True, verbose_name='registration number')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user can borrow books', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'library user',
                'verbose_name_plural': 'library users',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['registration_number'], name='users_libra_registr_fcc79b_idx'), models.Index(fields=['email'], name='users_libra_email_f0a959_idx')],
            },
        ),
    ]
