# Generated by Django 5.2.7 on 2025-11-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book', max_length=255, verbose_name='title')),
                ('author', models.CharField(help_text='The author(s) of the book', max_length=255, verbose_name='author')),
                ('isbn', models.CharField(help_text='International Standard Book Number', max_length=13, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, help_text='Publishing company', max_length=255, verbose_name='publisher')),
                ('publication_year', models.PositiveIntegerField(blank=True, help_text='Year the book was published', null=True, verbose_name='publication year')),
                ('category', models.CharField(blank=True, help_text='Genre or category of the book', max_length=100, verbose_name='category')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total copies available in the library', verbose_name='quantity')),
                ('available_quantity', models.PositiveIntegerField(default=1, help_text='Number of copies currently available for loan', verbose_name='available quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx'), models.Index(fields=['title'], name='books_book_title_d3218d_idx'), models.Index(fields=['author'], name='books_book_author_b941fe_idx')],
            },
        ),
    ]
