# Generated by Django 5.2.7 on 2025-11-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Book cover image', null=True, upload_to='books/covers/', verbose_name='cover image'),
        ),
    ]
