# Generated by Django 5.2.7 on 2025-11-04 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the book was borrowed', verbose_name='loan date')),
                ('due_date', models.DateField(help_text='Date when the book should be returned', verbose_name='due date')),
                ('return_date', models.DateField(blank=True, help_text='Actual date when the book was returned', null=True, verbose_name='return date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('renewed', 'Renewed')], default='active', help_text='Current status of the loan', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the loan', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('book', models.ForeignKey(help_text='Reference to the borrowed book', on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='books.book', verbose_name='book')),
                ('user', models.ForeignKey(help_text='Reference to the library user who borrowed the book', on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='users.libraryuser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ['-loan_date'],
                'indexes': [models.Index(fields=['status'], name='loans_loan_status_962e99_idx'), models.Index(fields=['loan_date'], name='loans_loan_loan_da_8d8a18_idx'), models.Index(fields=['due_date'], name='loans_loan_due_dat_1042a5_idx')],
            },
        ),
    ]
